{
	"version": 1573554028,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/road_background.png",
		"images/road.png",
		"images/dundoor.png",
		"images/exit-sheet0.png",
		"images/entry-sheet0.png",
		"images/enemy_bat_1-sheet0.png",
		"images/enemy_bat_1-sheet1.png",
		"images/enemy_bat_1-sheet2.png",
		"images/sword-sheet0.png",
		"images/game_background.png",
		"images/invic_wall-sheet0.png",
		"images/block_walk_f-sheet0.png",
		"images/dir-sheet0.png",
		"images/enemy_skeleton-sheet0.png",
		"images/enemy_skeleton-sheet1.png",
		"images/hp.png",
		"images/box.png",
		"images/game_name.png",
		"images/tilemap.png",
		"images/decoration.png",
		"images/sign-sheet0.png",
		"images/check_sign-sheet0.png",
		"images/box_hp_bar-sheet0.png",
		"images/sprite-sheet0.png",
		"images/dmg-sheet0.png",
		"media/angel's breath.ogg",
		"media/grassland adventure.ogg",
		"media/warring swords.ogg",
		"media/darkened winds.ogg",
		"media/shimmerlight skies.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}